services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/sonarr:/config
      - ${DATA}:/data    
    ports:
      - ${PORT}:8989
    networks: 
      - my_default
    networks: 
      - my_default
      - gluetun_default
    restart: unless-stopped

networks:
  my_default:
    external: true
  gluetun_default:
    external: true