---
networks:
  my_default:
    external: true

services:
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/tautulli:/config
      - ${APPDATA}/plex:/plex:ro
    ports:
      - 8181:8181
    networks:
      - my_default
    restart: unless-stopped
