services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${PORT2}
    volumes:
      - ${APPDATA}/qbittorrent:/config
      - ${DATA}/downloads:/downloads
    # ports:
    #   - ${PORT1}:8080
    #   - ${PORT2}:${PORT2}
    #   - ${PORT2}:${PORT2}/udp
    network_mode: container:gluetun 
    restart: unless-stopped