---
networks:
  my_default:
    external: true

services:
  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ={TZ}
    volumes:
      - ${APPDATA}/overseerr:/config
    networks:
      - my_default
    ports:
      - 5055:5055
    restart: unless-stopped
