---
networks:
  my_default:
    external: true

services:
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/readarr:/config
      - ${DATA}:/data
    ports:
      - 8787:8787
    networks: 
      - my_default
    restart: unless-stopped
