---
networks:
  my_default:
    external: true

services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/prowlarr:/config
    ports:
      - 9696:9696
    networks: 
      - my_default
    restart: unless-stopped
