services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/prowlarr:/config
    ports:
      - ${PORT}:9696
    network_mode: ${NETWORK}
    restart: unless-stopped
