services:
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/plex:/config
      - ${DATA}/media:/data
    networks:
      - my_default
    ports:
      - 32400:32400
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri

networks:
  my_default:
    external: true