---
networks:
  my_default:
    external: true

services:
  doplarr:
    container_name: doplarr
    image: ghcr.io/hotio/doplarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISCORD__TOKEN=${DOPLARR_DISCORD_TOKEN}
      - OVERSEERR__API=${OVERSEERR_API}
      - OVERSEERR__URL=http://overseerr:5055
      - OVERSEERR__DEFAULT_ID=1 # Default User ID
    volumes:
      - ${APPDATA}/doplarr:/config
    networks: 
      - my_default
    restart: unless-stopped
