services:
  speedtest:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - OOKLA_EULA_GDPR=true
      - SPEEDTEST_SCHEDULE=${CRON_SCHEDULE}
    volumes:
      - ${APPDATA}/speedtest-tracker:/config
    ports:
      - ${PORT}:80
    network_mode: bridge
    restart: unless-stopped
