services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/radarr:/config
      - ${DATA}:/data
    ports:
      - ${PORT}:7878
    networks: 
      - my_default
      - gluetun_default
    restart: unless-stopped

networks:
  my_default:
    external: true
  gluetun_default:
    external: true