---
volumes:
  db:

networks:
  my_default:
    external: true

services:
  mdblistarr:
    container_name: mdblistarr
    image: linaspurinis/mdblistarr:latest
    environment:
      - PORT=5353
    volumes:
      - db:/usr/src/db/
    networks: 
      - my_default
    ports:
      - 5353:5353
