---
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - SCRUTINY_WEB_INFLUXDB_TOKEN=${RANDOM_TOKEN}
      - SCRUTINY_WEB_INFLUXDB_INIT_USERNAME=${USERNAME}
      - SCRUTINY_WEB_INFLUXDB_INIT_PASSWORD=${PASSWORD}
    volumes:
      - /run/udev:/run/udev:ro
      - ${APPDATA}/scrutiny:/opt/scrutiny/config
      - ${APPDATA}/scrutiny/influxdb:/opt/scrutiny/influxdb
    ports:
      - 6080:8080
      - 8086:8086
    network_mode: bridge
    restart: unless-stopped
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sdea:/dev/sdea
      - /dev/sdeb:/dev/sdeb
      - /dev/sdec:/dev/sdec
      - /dev/sded:/dev/sded
      