services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - "6090:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /volume1/docker/data/scrutiny:/opt/scrutiny/config
      - /volume1/docker/data/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sdea:/dev/sdea
      - /dev/sdeb:/dev/sdeb
      - /dev/sdec:/dev/sdec
      - /dev/sded:/dev/sded
    environment:
      - SCRUTINY_WEB_INFLUXDB_TOKEN=${RANDOM_TOKEN}
      - SCRUTINY_WEB_INFLUXDB_INIT_USERNAME=${USERNAME}
      - SCRUTINY_WEB_INFLUXDB_INIT_PASSWORD=${PASSWORD}
    restart: unless-stopped
