---
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    network_mode: bridge
    restart: unless-stopped
