services:
  firefox:
    container_name: firefox
    image: lscr.io/linuxserver/firefox:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/firefox:/config
    shm_size: "1gb"
    ports:
      - ${PORT1}:3000
      - ${PORT2}:3001
    network_mode: bridge
    restart: unless-stopped