services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/bazarr:/config
      - ${DATA}/media:/data/media
    ports:
      - ${PORT}:6767
    network_mode: bridge
    restart: unless-stopped