---
networks:
  my_default:
    external: true

services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/bazarr:/config
      - ${DATA}/media:/data/media
    ports:
      - 6767:6767
    networks: 
      - my_default
    restart: unless-stopped
