---
services:
  peanut:
    container_name: peanut
    image: brandawg93/peanut
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NUT_HOST=${HOST_IP}
      - NUT_PORT=3493
      - WEB_PORT=8800
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    network_mode: host # Needed to allow use NAS IP in Hardware & Power > UPS > Permitted Diskstation Devices
    restart: unless-stopped
    