services:
  peanut:
    container_name: peanut
    image: brandawg93/peanut
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NUT_HOST=${HOST_IP}
      - NUT_PORT=3493
      - WEB_PORT=8080
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    ports:
      - ${PORT}:8080
    network_mode: bridge
    restart: unless-stopped