services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${APPDATA}/lidarr:/config
      - ${DATA}:/data
    ports:
      - ${PORT}:8686
    networks: 
      - my_default
      - gluetun_default
    restart: unless-stopped

networks:
  my_default:
    external: true
  gluetun_default:
    external: true