services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=${PROVIDER}
      - OPENVPN_USER=${USERNAME}
      - OPENVPN_PASSWORD=${PASSWORD}
      - TZ=${TZ}
      - SERVER_COUNTRIES=${SERVERCOUNTRIES}
      - SERVER_CITIES=${SERVERCITIES}
      - PUBLICIP_API_TOKEN=${PUBLICIP_API_TOKEN}
      - UPDATER_PERIOD=24h
    volumes:
      - ${APPDATA}/gluetun:/gluetun
    ports:
      - ${PORT1}:8888
      - ${PORT2}:8388
      - ${PORT2}:8388/udp
      - ${PORT3}:8080 # qbitorrent port
      - ${PORT4}:${PORT4} # qbitorrent torrent port
      - ${PORT4}:${PORT4}/udp # qbitorrent torrent port udp
      - ${PORT5}:8191 # flaresolverr port
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
