---
services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - UMASK=002
    volumes:
      - ${DATA}/downloads/metube:/downloads
    ports:
      - 8081:8081
    network_mode: bridge
    restart: unless-stopped
