services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    environment:
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - ${DATA}/metube:/downloads
    ports:
      - ${PORT}:8081
    network_mode: bridge
    restart: unless-stopped