---
networks:
  my_default:
    external: true

services:
  kometa:
    container_name: kometa
    image: kometateam/kometa
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - KOMETA_TESTS=true
      # - KOMETA_RUN=true
      # - KOMETA_METADATA_ONLY=true
      # - KOMETA_COLLECTIONS_ONLY=true
      # - KOMETA_PLAYLISTS_ONLY=true
      # - KOMETA_OPERATIONS_ONLY=true
      # - KOMETA_OVERLAYS_ONLY=true
      - KOMETA_TIMES=10:00
      - KOMETA_PLEX_IP=http://plex:32400
      - KOMETA_PLEX_TKN=${PLEX_TKN}
      - KOMETA_TMDB_API=${TMDB_API}
      - KOMETA_MDBLIST_API=${MDBLIST_API}
      - KOMETA_TRAKT_ID=${KOMETA_TRAKT_ID}
      - KOMETA_TRAKT_SECRET=${KOMETA_TRAKT_SECRET}
      - KOMETA_TAUTULLI_IP=http://tautulli:8181
      - KOMETA_TAUTULLI_API=${TAUTULLI_API}
      - KOMETA_RADARR_IP=http://radarr:7878
      - KOMETA_RADARR_API=${RADARR_API}
      - KOMETA_SONARR_IP=http://sonarr:8989
      - KOMETA_SONARR_API=${SONARR_API}
      - KOMETA_WEBHOOK=${KOMETA_WEBHOOK}
    volumes:
      - ${APPDATA}/kometa:/config
    networks:
      - my_default
    restart: unless-stopped
